In [37]:
import KNN
import numpy as np
import operator as op

#### 1、将每一个32* 32的二进制图像矩阵都转化成1* 1024的向量

In [38]:
def img2vector(filename):
    returnVect=np.zeros((1,1024))
    fr=open(filename)
    for i in range(32):
        lineStr=fr.readline()
        for j in range(32):
            returnVect[0,32*i+j]=int(lineStr[j])
    return returnVect

In [39]:
testVector=img2vector('0_13.txt')  # 测试img2vector函数

In [40]:
testVector[0,0:31]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2、测试算法

In [41]:
from os import listdir
def handwritingClassTest():
    hwLabels=[] # 创建空向量，作为训练集标签向量
    trainingFileList=listdir('E:/pythonStudy/MachineLearingInAction/machinelearninginaction/Ch02/trainingDigits')  # 获取训练集文件目录
    m=len(trainingFileList)
    traingMat=np.zeros((m,1024)) # 创建训练集矩阵
    for i in range(m):  # 对于每个训练数据，做如下处理
        fileNameStr=trainingFileList[i]
        fileStr=fileNameStr.split('_')[0]
        classNumStr=int(fileStr.split('.')[0])  # 获得每个文件的类标签（即文件名的开始数字）
        hwLabels.append(classNumStr)  # 将类标签添加到hwLabels中
        # 将每个处理完的训练数据添加到训练样本
        traingMat[i,:]=img2vector('E:/pythonStudy/MachineLearingInAction/machinelearninginaction/Ch02/trainingDigits/%s' % fileNameStr)  
    
    # 测试样本
    testFileList=listdir('E:/pythonStudy/MachineLearingInAction/machinelearninginaction/Ch02/trainingDigits')  
    errorCount=0.0
    mTest=len(testFileList)
    for i in range(mTest):
        fileNameStr=testFileList[i]
        fileStr=fileNameStr.split('.')[0]
        classNumStr=int(fileStr.split('_')[0])
        vectorUnderTest=img2vector('E:/pythonStudy/MachineLearingInAction/machinelearninginaction/Ch02/trainingDigits/%s' % fileNameStr)
        # 使用KNN算法模型进行训练
        classifilerResult=KNN.classify0(vectorUnderTest,traingMat,hwLabels,3)
        print ("the classifier came back with: %d, the real answer is: %d" % (classifilerResult,classNumStr))
        if(classifilerResult != classNumStr) : errorCount +=1.0
    print ("\nthe total number of errors is: %d" % errorCount)
    print ("\nthe total error rate is: %d" % (errorCount/float(mTest)))

In [42]:
handwritingClassTest()

[ 0.         12.16552506 12.4498996  ... 18.08314132 15.16575089
 16.88194302]
[   0  112   63 ...  321  266 1235]
[(0, 3)]
the classifier came back with: 0, the real answer is: 0
[12.16552506  0.         11.09053651 ... 19.         15.42724862
 16.09347694]
[   1    6   54 ... 1379 1444  266]
[(0, 3)]
the classifier came back with: 0, the real answer is: 0
[12.4498996  11.09053651  0.         ... 18.         14.59451952
 14.2126704 ]
[   2   29  172 ... 1357 1436 1497]
[(0, 3)]
the classifier came back with: 0, the real answer is: 0
[11.53256259 10.81665383  9.79795897 ... 17.3781472  15.
 14.4222051 ]
[   3   51  132 ... 1441 1785  266]
[(0, 3)]
the classifier came back with: 0, the real answer is: 0
[11.61895004 12.20655562 10.29563014 ... 16.97056275 15.13274595
 14.89966443]
[  4  12   3 ... 559 321 690]
[(0, 3)]
the classifier came back with: 0, the real answer is: 0
[12.36931688 10.81665383 10.39230485 ... 17.1464282  14.52583905
 15.55634919]
[   5   97   12 ... 1477  266 1497]