### 使用梯度上升找到最佳参数

#### 1、logistic回归梯度上升优化算法

In [41]:
import numpy as np
def loadDataSet():
    dataMat=[]
    labelMat=[]
    fr = open("E:/pythonStudy/MachineLearingInAction/machinelearninginaction/Ch05/testSet.txt")
    for line in fr.readlines():
        lineArr=line.strip().split()
        dataMat.append([1.0,float(lineArr[0]),float(lineArr[1])])
        labelMat.append(int(lineArr[2]))
    return dataMat,labelMat

# sigmoid函数
def sigmoid(inX):
    return 1.0/(1+np.exp(-inX))

# 梯度上升算法的主要逻辑
def gradAscent(dataMatIn,classLabels):
    dataMatrix=np.mat(dataMatIn) # 转换成Numpy矩阵格式
    labelMat=np.mat(classmethod).transpose() # 对1*100的矩阵做转置
    m,n=np.shape(dataMatrix)
    alpha=0.001 # 梯度上升算法的步长
    maxCycles=500 # 循环次数
    weights=np.ones((n,1))
    for k in range(maxCycles):
        h=sigmoid(dataMatrix*weights) # 矩阵相乘        
        error=labelMat - h # 真实类别和预测类别的差值
        weights=weights+alpha*dataMatrix.transpose()*error # 回归系数
    return weights

In [42]:
# 测试梯度上升算法
dataArr,labelMat=loadDataSet()
gradAscent(dataArr,labelMat)

TypeError: unsupported operand type(s) for -: 'type' and 'float'

#### 2、画出决策边界

In [ ]:
def plotBestFit(weights):
    import matplotlib.pyplot as plt
    dataMat,labelMat=loadDataSet()
    dataArr=array(dataMat)
    n=np.shape(dataArr)[0]
    xcord1=[];ycord1=[]
    xcord2=[];ycord2=[]
    for i in range(n):
        if int(labelMat[i])==1:
            xcord1.append(dataArr[i,1])
            ycord1.append(dataArr[i,2])
        else:
            xcord2.append(dataArr[i,1])
            ycord2.append(dataArr[i,2])
    fig=plt.figure()
    ax=fig.add_subplot(111)
    ax.scatter(xcord1,ycord1,s=30,x='red',marker='s')
    ax.scatter(xcord2,ycord2,s=30,c='green')
    x=np.arange(-3.0,3.0,0.1)
    ax.plot(x,y)
    plt.xlabel('X1')
    plt.ylabel('X2')
    plt.show()

In [ ]:
weights=gradAscent(dataArr,labelMat)
plotBestFit(weights.getA())

#### 3、改进的随机梯度上升算法

In [45]:
def stocGradAscent1(dataMatrix,classLabels,numIter=150):
    m,n=np.shape(dataMatrix) # shape(dataMatrix)返回dataMatrix的行数和列数：m=100，n=3
    weights=np.ones(n) # 1*n列的单位矩阵
    for j in range(5):
        dataIndex=range(5)
        for i in range(5):
            alpha=4/(1.0+j+i)+0.01
            randIndex=int(np.random.uniform(0,len(dataIndex))) # uniform 随机生成下一个实数，在[0，len(dataIndex)]范围之内
            #print (randIndex)
            h=sigmoid(sum(dataMatrix[randIndex]*weights)) # 利用sigmoid函数计算随机样本和回归系数乘积的值，即为z
            #print (h)
            error=classLabels[randIndex]-h  # 计算误差
            print (error)
            weights=weights+alpha*error*dataMatrix[randIndex] # 更新回归系数
            print ("weights")
            print (weights)
            del(list(dataIndex)[randIndex]) # 将这个训练样本删除
    return weights

In [46]:
dataArr,labelMat=loadDataSet()
#print (dataArr)
#print ("-------------")
#print (np.array(dataArr))
#print ("-------------")
#print (labelMat)
weights=stocGradAscent1(np.array(dataArr),labelMat) # 标准化为numpy的数组形式
weights

-0.9989208285995589
weights
[ -3.00567252   6.29698518 -27.65198672]
-1.3023238012805805e-82
weights
[ -3.00567252   6.29698518 -27.65198672]
-7.616650913084453e-171
weights
[ -3.00567252   6.29698518 -27.65198672]
-1.509870942203388e-91
weights
[ -3.00567252   6.29698518 -27.65198672]
1.0
weights
[ -2.19567252   5.16652164 -23.87532851]
-8.164343113883002e-79
weights
[ -2.19567252   5.16652164 -23.87532851]
-3.63327031222827e-71
weights
[ -2.19567252   5.16652164 -23.87532851]
-1.9578046787278736e-147
weights
[ -2.19567252   5.16652164 -23.87532851]
-1.9578046787278736e-147
weights
[ -2.19567252   5.16652164 -23.87532851]
-2.3510976767921003e-115
weights
[ -2.19567252   5.16652164 -23.87532851]
-2.3510976767921003e-115
weights
[ -2.19567252   5.16652164 -23.87532851]
-8.164343113883002e-79
weights
[ -2.19567252   5.16652164 -23.87532851]
-1.9578046787278736e-147
weights
[ -2.19567252   5.16652164 -23.87532851]
-2.3510976767921003e-115
weights
[ -2.19567252   5.16652164 -23.87532851]
-

array([ -1.68567252,   4.4547483 , -21.4974326 ])